public with sharing class NewTask {
    public String Subject {get; set;}
    public String description {get; set;}
    
    public String whoId {get; set;}
    public String whoName {get; set;}
    public String whoIdType {get; set;}

    public String whatId {get; set;}
    public String whatName {get; set;}
    public String whatIdType {get; set;}

    public String priority {get; set;}
    public String status {get; set;}
    public String selectObjType {get; set;}

    public String callId {get;set;}
    public String callType {get;set;}
    public String recURL {get;set;}

    public String startTime {get;set;}
    public String endTime {get;set;}

    public String cphone {get;set;}

    public String callResult{get;set;}

    public Boolean psersonAccount{get;set;}
}