public with sharing class SRC_SFDCCaseRestWrapper {

    public class ReceiveJson {
        public Integer companySeq;
    }
    
    public class ReturnJson {
        public String AUDType;
        public String CrtDateTime;
        public Integer CompanySeq;
        public String CRMASSeq;
        public Integer OrderSeq;
        public String ASReqDate;
        public String RecvMobileNo;
        public String RecvAddr;
        public Integer UMTroubleType;
        public Integer UMItemType;
        public Integer UMChargeType;
        public String IsExchange;
        public String ShipNo2;
        public String ShipNo3;
        public String ShipNo4;
        public String ASShipNo2;
        public String ReturnShipNo;
        public Integer ItemSeq;
        public String ItemName;
        public String ItemNo;
        public Decimal BOMQty;
        public Decimal NeedQty;
        public String SalesRemark;
    }
}